// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: wal.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wal) Reset() {
	*x = Wal{}
	mi := &file_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wal) ProtoMessage() {}

func (x *Wal) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wal.ProtoReflect.Descriptor instead.
func (*Wal) Descriptor() ([]byte, []int) {
	return file_wal_proto_rawDescGZIP(), []int{0}
}

func (x *Wal) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Wal) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_wal_proto protoreflect.FileDescriptor

const file_wal_proto_rawDesc = "" +
	"\n" +
	"\twal.proto\"-\n" +
	"\x03Wal\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueB\x04Z\x02./b\x06proto3"

var (
	file_wal_proto_rawDescOnce sync.Once
	file_wal_proto_rawDescData []byte
)

func file_wal_proto_rawDescGZIP() []byte {
	file_wal_proto_rawDescOnce.Do(func() {
		file_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wal_proto_rawDesc), len(file_wal_proto_rawDesc)))
	})
	return file_wal_proto_rawDescData
}

var file_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wal_proto_goTypes = []any{
	(*Wal)(nil), // 0: Wal
}
var file_wal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wal_proto_init() }
func file_wal_proto_init() {
	if File_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wal_proto_rawDesc), len(file_wal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wal_proto_goTypes,
		DependencyIndexes: file_wal_proto_depIdxs,
		MessageInfos:      file_wal_proto_msgTypes,
	}.Build()
	File_wal_proto = out.File
	file_wal_proto_goTypes = nil
	file_wal_proto_depIdxs = nil
}
